export const furnitureCategories = [
  { name: 'Sofás y Sillones', slug: 'sofas', description: 'Sofás, sillones y chaiselongues para tu salón' },
  { name: 'Sillas y Taburetes', slug: 'sillas', description: 'Sillas de comedor, taburetes y sillas de diseño' },
  { name: 'Mesas', slug: 'mesas', description: 'Mesas de comedor, mesas de centro y auxiliares' },
  { name: 'Camas y Cabeceros', slug: 'camas', description: 'Camas, somiers y cabeceros para tu dormitorio' },
  { name: 'Armarios y Cómodas', slug: 'armarios', description: 'Armarios roperos, cómodas y cajoneras' },
  { name: 'Estanterías', slug: 'estanterias', description: 'Estanterías, librerías y módulos de almacenamiento' },
  { name: 'Escritorios', slug: 'escritorios', description: 'Escritorios, mesas de trabajo y despacho en casa' },
  { name: 'Decoración', slug: 'decoracion', description: 'Lámparas, alfombras y elementos decorativos' },
];

export interface FurnitureProduct {
  title: string;
  description: string;
  price: number;
  inStock: number;
  slug: string;
  categorySlug: string;
  material: string;
  dimensions: string;
  color: string;
  weight: number;
  tags: string[];
  imageUrl: string;
}

export const furnitureProducts: FurnitureProduct[] = [
  // SOFÁS
  {
    title: 'Sofá Nórdico 3 Plazas',
    description: 'Sofá de estilo escandinavo con estructura de madera de haya y tapizado en lino natural. Perfectamente dimensionado para salones modernos.',
    price: 899.99,
    inStock: 8,
    slug: 'sofa-nordico-3-plazas',
    categorySlug: 'sofas',
    material: 'Madera de haya y lino',
    dimensions: '220x90x75 cm',
    color: 'Beige natural',
    weight: 42,
    tags: ['nórdico', 'escandinavo', 'salón', 'lino'],
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
  {
    title: 'Sillón Relax Premium',
    description: 'Sillón reclinable con reposacabezas regulable y reposapiés integrado. Tapizado en piel sintética de alta calidad.',
    price: 499.00,
    inStock: 12,
    slug: 'sillon-relax-premium',
    categorySlug: 'sofas',
    material: 'Piel sintética y espuma HR',
    dimensions: '85x90x100 cm',
    color: 'Marrón cognac',
    weight: 28,
    tags: ['relax', 'reclinable', 'descanso'],
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
  },
  {
    title: 'Chaiselongue Modular',
    description: 'Chaiselongue modular con configuración reversible. Marco de madera maciza y tapizado en tejido antimanchas.',
    price: 1199.00,
    inStock: 5,
    slug: 'chaiselongue-modular',
    categorySlug: 'sofas',
    material: 'Madera maciza y tejido antimanchas',
    dimensions: '280x160x75 cm',
    color: 'Gris antracita',
    weight: 65,
    tags: ['modular', 'chaiselongue', 'salón', 'diseño'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
  },

  // SILLAS
  {
    title: 'Silla de Comedor Tulip',
    description: 'Silla de comedor de diseño moderno con asiento acolchado y patas de madera de roble. Disponible en varios colores.',
    price: 129.00,
    inStock: 30,
    slug: 'silla-comedor-tulip',
    categorySlug: 'sillas',
    material: 'Roble y tela',
    dimensions: '45x50x85 cm',
    color: 'Roble natural',
    weight: 4.5,
    tags: ['comedor', 'diseño', 'roble'],
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
  },
  {
    title: 'Silla Eames Replica',
    description: 'Silla de plástico moldeado con patas de madera en acabado natural. Diseño atemporal para cualquier espacio.',
    price: 89.00,
    inStock: 45,
    slug: 'silla-eames-replica',
    categorySlug: 'sillas',
    material: 'Plástico ABS y madera',
    dimensions: '47x49x83 cm',
    color: 'Blanco',
    weight: 3.2,
    tags: ['diseño', 'clásico', 'plástico', 'versátil'],
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
  },
  {
    title: 'Taburete Bar Industrial',
    description: 'Taburete de barra estilo industrial con estructura de metal negro mate y asiento de madera maciza de pino.',
    price: 75.00,
    inStock: 20,
    slug: 'taburete-bar-industrial',
    categorySlug: 'sillas',
    material: 'Metal y pino macizo',
    dimensions: '38x38x75 cm',
    color: 'Negro y madera natural',
    weight: 5.8,
    tags: ['bar', 'industrial', 'cocina', 'metal'],
    imageUrl: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=800&q=80',
  },

  // MESAS
  {
    title: 'Mesa de Comedor Extensible',
    description: 'Mesa de comedor extensible de 4 a 8 comensales. Tapa de madera de roble macizo con patas de acero inoxidable.',
    price: 749.00,
    inStock: 7,
    slug: 'mesa-comedor-extensible',
    categorySlug: 'mesas',
    material: 'Roble macizo y acero',
    dimensions: '160-240x90x76 cm',
    color: 'Roble claro',
    weight: 55,
    tags: ['comedor', 'extensible', 'roble', 'familias'],
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
  {
    title: 'Mesa de Centro Mármol',
    description: 'Elegante mesa de centro con tapa de mármol blanco de Carrara y base de latón dorado. Pieza artesanal única.',
    price: 599.00,
    inStock: 4,
    slug: 'mesa-centro-marmol',
    categorySlug: 'mesas',
    material: 'Mármol Carrara y latón',
    dimensions: '100x60x42 cm',
    color: 'Blanco y dorado',
    weight: 30,
    tags: ['mármol', 'lujo', 'salón', 'centro'],
    imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=800&q=80',
  },
  {
    title: 'Mesa Auxiliar Rattan',
    description: 'Mesa auxiliar artesanal tejida en rattan natural con estructura de bambú. Ideal para complementar cualquier estancia.',
    price: 149.00,
    inStock: 15,
    slug: 'mesa-auxiliar-rattan',
    categorySlug: 'mesas',
    material: 'Rattan y bambú',
    dimensions: '50x50x55 cm',
    color: 'Natural',
    weight: 3.5,
    tags: ['rattan', 'artesanal', 'bohemio', 'auxiliar'],
    imageUrl: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&q=80',
  },

  // CAMAS
  {
    title: 'Cama Matrimonial con Cabecero',
    description: 'Cama de matrimonio (180x200 cm) con cabecero tapizado en terciopelo azul. Incluye somier de láminas.',
    price: 1299.00,
    inStock: 6,
    slug: 'cama-matrimonial-cabecero',
    categorySlug: 'camas',
    material: 'Madera maciza y terciopelo',
    dimensions: '200x220x110 cm',
    color: 'Azul noche',
    weight: 75,
    tags: ['matrimonial', 'terciopelo', 'dormitorio', 'moderno'],
    imageUrl: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&q=80',
  },
  {
    title: 'Cama Nórdica con Cajones',
    description: 'Cama individual o doble con almacenamiento integrado en cajones. Estructura de pino pintado en blanco.',
    price: 649.00,
    inStock: 10,
    slug: 'cama-nordica-cajones',
    categorySlug: 'camas',
    material: 'Pino macizo pintado',
    dimensions: '160x210x90 cm',
    color: 'Blanco',
    weight: 60,
    tags: ['almacenamiento', 'cajones', 'dormitorio', 'nórdico'],
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
  },

  // ARMARIOS
  {
    title: 'Armario Ropero 3 Puertas',
    description: 'Armario ropero de 3 puertas batientes con espejo central. Interior con barra colgador y estantes regulables.',
    price: 899.00,
    inStock: 5,
    slug: 'armario-ropero-3-puertas',
    categorySlug: 'armarios',
    material: 'DM lacado y espejo',
    dimensions: '150x60x210 cm',
    color: 'Blanco brillante',
    weight: 90,
    tags: ['armario', 'espejo', 'dormitorio', 'almacenaje'],
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
  },
  {
    title: 'Cómoda 6 Cajones Vintage',
    description: 'Cómoda de 6 cajones con acabado vintage envejecido. Tiradores de latón envejecido incluidos.',
    price: 349.00,
    inStock: 9,
    slug: 'comoda-6-cajones-vintage',
    categorySlug: 'armarios',
    material: 'Madera de pino',
    dimensions: '100x45x90 cm',
    color: 'Blanco envejecido',
    weight: 35,
    tags: ['vintage', 'cajones', 'dormitorio', 'retro'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
  },

  // ESTANTERÍAS
  {
    title: 'Librería Modular Industrial',
    description: 'Librería modular de 5 estantes en estilo industrial. Estructura de hierro negro mate con estantes de madera maciza.',
    price: 299.00,
    inStock: 14,
    slug: 'libreria-modular-industrial',
    categorySlug: 'estanterias',
    material: 'Hierro y madera de roble',
    dimensions: '80x30x180 cm',
    color: 'Negro y roble',
    weight: 22,
    tags: ['librería', 'industrial', 'estantería', 'salón'],
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
  },
  {
    title: 'Estantería Flotante Set 3',
    description: 'Set de 3 estanterías flotantes de madera de pino. Instalación sencilla con sistema de fijación oculto.',
    price: 89.00,
    inStock: 25,
    slug: 'estanteria-flotante-set-3',
    categorySlug: 'estanterias',
    material: 'Pino macizo',
    dimensions: '60x20x3.5 cm cada una',
    color: 'Natural',
    weight: 6,
    tags: ['flotante', 'pared', 'decoración', 'almacenaje'],
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
  },

  // ESCRITORIOS
  {
    title: 'Escritorio Home Office Premium',
    description: 'Escritorio amplio con cajón lateral y bandeja para teclado. Ideal para trabajar desde casa con comodidad y estilo.',
    price: 449.00,
    inStock: 11,
    slug: 'escritorio-home-office-premium',
    categorySlug: 'escritorios',
    material: 'MDF lacado y metal',
    dimensions: '140x70x76 cm',
    color: 'Blanco y negro',
    weight: 35,
    tags: ['escritorio', 'trabajo', 'home office', 'moderno'],
    imageUrl: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
  },
  {
    title: 'Mesa de Estudio Plegable',
    description: 'Mesa plegable compacta y funcional para pequeños espacios. Se pliega completamente para guardar sin ocupar espacio.',
    price: 149.00,
    inStock: 18,
    slug: 'mesa-estudio-plegable',
    categorySlug: 'escritorios',
    material: 'Madera y metal',
    dimensions: '90x50x75 cm',
    color: 'Blanco',
    weight: 12,
    tags: ['plegable', 'pequeño espacio', 'estudio', 'práctico'],
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
  },

  // DECORACIÓN
  {
    title: 'Alfombra Kilim Artesanal',
    description: 'Alfombra de lana tejida a mano con motivos geométricos. Procedente de talleres artesanos.',
    price: 279.00,
    inStock: 7,
    slug: 'alfombra-kilim-artesanal',
    categorySlug: 'decoracion',
    material: 'Lana 100% natural',
    dimensions: '160x230 cm',
    color: 'Multicolor tierra',
    weight: 3.8,
    tags: ['alfombra', 'kilim', 'artesanal', 'bohemio'],
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
];
